//
//  EnvironmentInjectionCrashDemo.swift
//  Statoscope
//
//  Demonstrates the @EnvironmentObject propagation failure that occurs when
//  _ReducerChildViewConnector is used as a NavigationLink destination.
//
//  Preview "Crash reproduction": shows the exact setup that crashes on device/simulator.
//  The crash message is:
//    Fatal error: No ObservableObject of type ParentStore found.
//    A View.environmentObject(_:) for ParentStore may be missing as an ancestor of this view.
//
//  NOTE: Xcode Previews may not crash here because the Preview host injects its own
//  environment. Run on a simulator or device to see the crash.
//

#if DEBUG
import SwiftUI

// MARK: - Minimal stores for the demo

/// Minimal ReducerStoreProtocol conforming parent store
final class _DemoParentStore: ObservableObject, ReducerStoreProtocol {
    struct State {
        var title: String = "Parent"
        var child: _DemoChildStore? = nil
    }
    enum When {
        case showChild
        case hideChild
    }

    @Published var state: State = State()

    init() {}

    func _dispatch(_ when: When) {
        switch when {
        case .showChild:
            state.child = _DemoChildStore()
        case .hideChild:
            state.child = nil
        }
        objectWillChange.send()
    }

    // KeyPath accessor mirroring what @Reducer macro generates
    var child: _DemoChildStore? { state.child }
}

/// Minimal ReducerStoreProtocol conforming child store
final class _DemoChildStore: ObservableObject, ReducerStoreProtocol {
    struct State {
        var label: String = "Child view rendered ✓"
    }
    enum When {}

    @Published var state: State = State()

    func _dispatch(_ when: When) {}
}

// MARK: - Views

/// The child view — a StoreViewProtocol-like view
private struct _DemoChildPresentedView: View {
    let model: _DemoChildStore.State
    let send: (_DemoChildStore.When) -> Void

    var body: some View {
        VStack(spacing: 16) {
            Text(model.label)
                .font(.headline)
            Text("@EnvironmentObject was resolved successfully")
                .foregroundColor(.green)
        }
        .padding()
    }
}

// MARK: - Preview: crash reproduction

/// This view mirrors the pattern used in the real app:
///   - ReducerStoreView injects the parent store via .environmentObject
///   - The parent view uses navigation() + buildXXXView() (i.e. _ReducerChildViewConnector)
///   - The NavigationLink destination evaluates _ReducerChildViewConnector.body lazily
///   - On device/simulator that lazy evaluation finds no @EnvironmentObject → crash
private struct _DemoParentView: View {
    let model: _DemoParentStore.State
    let send: (_DemoParentStore.When) -> Void

    var body: some View {
        VStack(spacing: 24) {
            Text(model.title)
                .font(.title)

            Button("Navigate to child") {
                send(.showChild)
            }

            // This mirrors HomeReducer.buildMyAccountView(content:)
            // _ReducerChildViewConnector resolves @EnvironmentObject in its body,
            // which is evaluated lazily as the NavigationLink destination.
            NavigationLink(
                isActive: Binding(
                    get: { model.child != nil },
                    set: { if !$0 { send(.hideChild) } }
                ),
                destination: {
                    // ← body of _ReducerChildViewConnector evaluated here, AFTER push
                    // On device: @EnvironmentObject lookup for _DemoParentStore fails → CRASH
                    _ReducerChildViewConnector<_DemoParentStore, _DemoChildStore, _DemoChildPresentedView>(
                        storeKeyPath: \.child,
                        content: _DemoChildPresentedView.init
                    )
                }
            ) {
                EmptyView()
            }
            #if !os(macOS)
            .isDetailLink(false)
            #endif

            Text("↑ Tapping the button above will crash on device/simulator\nbut may survive in Xcode Preview")
                .font(.caption)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
        }
        .padding()
        .navigationTitle("Demo — crash reproduction")
    }
}

#Preview("Crash reproduction — run on simulator to see crash") {
    // ReducerStoreView injects .environmentObject(store) — same as production setup
    let store = _DemoParentStore()
    return NavigationView {
        ReducerStoreView<_DemoParentStore, _StoreViewBridge>(store: store)
    }
}

// MARK: - Fix: _ReducerChildNavigationConnector (generated by @Reducer macro)

/// Demonstrates the recommended fix: use `Reducer.buildChildPresentedView(isPresented:content:)`
/// instead of `navigation(keyPath, dismissWhen:) { _ in Reducer.buildChildView(content:) }`.
///
/// `_ReducerChildNavigationConnector` IS the NavigationLink — it resolves `@EnvironmentObject`
/// in its own sibling body (non-lazy), captures the store reference, then the NavigationLink
/// destination uses that direct reference. No @EnvironmentObject lookup in the lazy context.
private struct _DemoFixedParentView: View {
    let model: _DemoParentStore.State
    let send: (_DemoParentStore.When) -> Void

    var body: some View {
        VStack(spacing: 24) {
            Text(model.title)
                .font(.title)

            Button("Navigate to child") {
                send(.showChild)
            }

            // ✅ This is what @Reducer macro now generates as buildChildPresentedView(dismissWhen:content:).
            // _ReducerChildNavigationConnector resolves @EnvironmentObject in its own body
            // (sibling render context — non-lazy), derives isPresented from the keypath,
            // and captures the store by direct reference for the lazy destination.
            _ReducerChildNavigationConnector<_DemoParentStore, _DemoChildStore, _DemoChildPresentedView>(
                storeKeyPath: \.child,
                dismissWhen: .hideChild,
                content: _DemoChildPresentedView.init
            )

            Text("↑ Works on device/simulator — NavigationLink is the connector itself")
                .font(.caption)
                .foregroundColor(.green)
                .multilineTextAlignment(.center)
        }
        .padding()
        .navigationTitle("Demo — macro fix")
    }
}

private struct _FixedStoreViewBridge: View, StoreViewProtocol {
    typealias State = _DemoParentStore.State
    typealias When = _DemoParentStore.When
    let model: State
    let send: (When) -> Void
    init(model: State, send: @escaping (When) -> Void) {
        self.model = model; self.send = send
    }
    var body: some View { _DemoFixedParentView(model: model, send: send) }
}

#Preview("Macro fix — buildXxxPresentedView(dismissWhen:content:)") {
    let store = _DemoParentStore()
    return NavigationView {
        ReducerStoreView<_DemoParentStore, _FixedStoreViewBridge>(store: store)
    }
}

// MARK: - Generic helper: capture @EnvironmentObject before any lazy evaluation

/// Resolves an @EnvironmentObject in its own body (sibling/normal render context),
/// then passes the already-captured reference into a @ViewBuilder closure.
/// Any lazy evaluation inside that closure (NavigationLink destination, sheet, etc.)
/// receives a direct reference — no @EnvironmentObject lookup needed inside the closure.
///
/// Usage:
///   EnvironmentObjectCapture<MyStore> { store in
///       NavigationLink(isActive: ..., destination: { DestView(store: store) }) { EmptyView() }
///   }
private struct EnvironmentObjectCapture<S: ObservableObject, Content: View>: View {
    @EnvironmentObject private var object: S          // resolved here, in sibling body ✓
    private let content: (S) -> Content

    init(_ type: S.Type = S.self, @ViewBuilder content: @escaping (S) -> Content) {
        self.content = content
    }

    var body: some View {
        content(object)   // object already captured — safe to use in any lazy closure
    }
}

/// Safe destination: uses @ObservedObject (direct reference), never @EnvironmentObject.
private struct _DemoChildStoreView: View {
    @ObservedObject var parentStore: _DemoParentStore

    var body: some View {
        if let childStore = parentStore.child {
            _DemoObservingChildView(store: childStore)
        }
    }
}

private struct _DemoObservingChildView: View {
    @ObservedObject var store: _DemoChildStore

    var body: some View {
        _DemoChildPresentedView(model: store.state, send: store._dispatch)
            .environmentObject(store)
    }
}

/// Working parent view — identical state/send signature as the crashing one.
private struct _DemoWorkingParentView: View {
    let model: _DemoParentStore.State
    let send: (_DemoParentStore.When) -> Void

    var body: some View {
        VStack(spacing: 24) {
            Text(model.title)
                .font(.title)

            Button("Navigate to child") {
                send(.showChild)
            }

            EnvironmentObjectCapture(_DemoParentStore.self) { parentStore in
                NavigationLink(
                    isActive: Binding(
                        get: { parentStore.child != nil },
                        set: { if !$0 { parentStore._dispatch(.hideChild) } }
                    ),
                    destination: {
                        _DemoChildStoreView(parentStore: parentStore)
                    }
                ) { EmptyView() }
                #if !os(macOS)
                .isDetailLink(false)
                #endif
            }

            Text("↑ Works on device/simulator — no crash")
                .font(.caption)
                .foregroundColor(.green)
                .multilineTextAlignment(.center)
        }
        .padding()
        .navigationTitle("Demo — working")
    }
}

#Preview("Working solution — sibling resolves env, destination uses @ObservedObject") {
    let store = _DemoParentStore()
    return NavigationView {
        ReducerStoreView<_DemoParentStore, _WorkingStoreViewBridge>(store: store)
    }
}

private struct _WorkingStoreViewBridge: View, StoreViewProtocol {
    typealias State = _DemoParentStore.State
    typealias When = _DemoParentStore.When
    let model: State
    let send: (When) -> Void
    init(model: State, send: @escaping (When) -> Void) {
        self.model = model; self.send = send
    }
    var body: some View { _DemoWorkingParentView(model: model, send: send) }
}

// MARK: - ReducerStoreView bridge for the crashing demo

/// Bridge that makes _DemoParentStore + _DemoParentView work with ReducerStoreView
private struct _StoreViewBridge: View, StoreViewProtocol {
    typealias State = _DemoParentStore.State
    typealias When = _DemoParentStore.When

    let model: State
    let send: (When) -> Void

    init(model: State, send: @escaping (When) -> Void) {
        self.model = model
        self.send = send
    }

    var body: some View {
        _DemoParentView(model: model, send: send)
    }
}

#endif
