//
//  ChildStoreSlots.swift
//  Statoscope
//

import Foundation

/// Protocol for the generated `ChildStores` accessor struct.
/// The `@Reducer` macro generates a conforming struct with typed properties for each `@SubState`.
public protocol ChildStoresProtocol {
    init(cache: [AnyHashable: AnyObject])
}

/// Default ChildStores for reducers with no `@SubState` children.
public struct EmptyChildStores: ChildStoresProtocol {
    public init(cache: [AnyHashable: AnyObject]) {}
}

/// Type-erased descriptor for a single `@SubState` child relationship.
///
/// `ParentState` is the parent reducer's `State` type.
/// All closures are generated by the `@Reducer` macro and capture the concrete child reducer type.
public struct AnyChildSlot<ParentState> {
    public let key: AnyHashable
    /// Returns true if the state's @SubState property has been assigned (isDirty).
    public let isDirty: (ParentState) -> Bool
    /// Returns true if the state's @SubState property holds a non-nil value.
    public let isPresent: (ParentState) -> Bool
    /// Creates a new child Store from the non-nil child state in parentState.
    public let create: (ParentState) -> any InjectionTreeNode
    /// Sends `defaultTrigger` to the child store if the reducer defines one.
    public let triggerDefault: (AnyObject) -> Void
    /// Resets the isDirty flag on the @SubState property.
    public let resetDirty: (inout ParentState) -> Void
    /// Injects the child store's raw state as a SubState(injectedValue:) into parentState.
    /// Receives nil when the child store does not exist yet.
    public let injectIntoParent: (AnyObject?, inout ParentState) -> Void
    /// Extracts the non-nil child state from parentState as Any.
    /// Used to pass the child's initial state to _applyChildSlotsRecursively without
    /// reading _rawState from the newly created store.
    public let extractChildState: (ParentState) -> Any

    public init(
        key: AnyHashable,
        isDirty: @escaping (ParentState) -> Bool,
        isPresent: @escaping (ParentState) -> Bool,
        create: @escaping (ParentState) -> any InjectionTreeNode,
        triggerDefault: @escaping (AnyObject) -> Void,
        resetDirty: @escaping (inout ParentState) -> Void,
        injectIntoParent: @escaping (AnyObject?, inout ParentState) -> Void,
        extractChildState: @escaping (ParentState) -> Any
    ) {
        self.key = key
        self.isDirty = isDirty
        self.isPresent = isPresent
        self.create = create
        self.triggerDefault = triggerDefault
        self.resetDirty = resetDirty
        self.injectIntoParent = injectIntoParent
        self.extractChildState = extractChildState
    }
}

/// Type-erased descriptor for a `@SuperState` or `@ReducerInjected` injection.
///
/// `ChildState` is the child reducer's `State` type.
/// The `inject` closure is generated by the `@Reducer` macro.
/// It receives the child Store (as AnyObject) and injects the parent state snapshot
/// or resolved dependency into the child state.
public struct AnySuperSlot<ChildState> {
    /// Injects into `state`. `store` is the child `Store<R>` passed as `AnyObject`.
    public let inject: (AnyObject, inout ChildState) -> Void

    public init(inject: @escaping (AnyObject, inout ChildState) -> Void) {
        self.inject = inject
    }
}
