//
//  Store.swift
//  Statoscope
//

import Foundation
import Combine

/// Generic store for any `Reducer` type.
///
/// `Store<R>` replaces the per-reducer `Store` classes previously generated by the `@Reducer`
/// macro. It is fully generic: child store lifecycle, parent state injection, and effect
/// management are driven by the `_childSlots` and `_superSlots` arrays that the `@Reducer`
/// macro generates on the `Reducer` type.
///
/// ## Usage
/// ```swift
/// @Reducer
/// struct CounterReducer {
///     struct State { var count: Int = 0 }
///     enum When { case increment }
///     static func update(_ when: When, state: inout State, ...) throws {
///         state.count += 1
///     }
/// }
///
/// // The macro generates: public typealias Store = Statoscope.Store<CounterReducer>
/// let store = CounterReducer.Store(initialState: .init())
/// store.send(.increment)
/// print(store.state.count) // 1
/// ```
public final class Store<R: Reducer>: Statostore, ObservableObject {

    public typealias When = R.When
    public typealias ScopeImpl = Store<R>

    // MARK: - State storage

    /// Raw state storage. @Published triggers SwiftUI objectWillChange.
    /// Public so macro-generated `injectIntoParent` closures can access `childStore._rawState`
    /// without requiring @_spi imports in user code.
    @Published public var _rawState: R.State

    /// Child store cache — keyed by `AnyChildSlot.key`. Managed during `update()`.
    var _childCache: [AnyHashable: AnyObject] = [:]

    /// Retains the `AnyCancellable`s from `@SuperState(observed: true)` relays for this
    /// store's lifetime. Populated exactly once, in `_wireSuperSlots()`, when this store is
    /// created as someone's child.
    private var _superObservers: [AnyCancellable] = []

    // Recursively applies child slots using `initialState` (passed by the caller) rather
    // than reading _rawState, so the caller controls which state drives the recursion.
    // Critical: must run before the `state` computed getter resets dirty flags via injectIntoParent.
    fileprivate func _applyChildSlotsRecursively(state initialState: Any, triggerDefaults: Bool) {
        guard var typedState = initialState as? R.State else { return }
        applyChildSlots(&typedState, triggerDefaults: triggerDefaults)
    }

    // MARK: - Public API

    /// Computed state: injects live child states and parent state snapshots before returning.
    ///
    /// Reads `_rawState`, then applies each `_childSlots` `injectIntoParent` closure
    /// (so `state.child` always reflects the current child store's data) and each
    /// `_superSlots` `inject` closure (so `state.parent` always reflects the current
    /// parent store's data). The raw storage is unmodified.
    public var state: R.State {
        get {
            let childSlots = R._childSlots
            let superSlots = R._superSlots
            guard !childSlots.isEmpty || !superSlots.isEmpty else { return _rawState }
            var s = _rawState
            for slot in childSlots {
                slot.injectIntoParent(_childCache[slot.key], &s)
            }
            for slot in superSlots {
                slot.inject(self, &s)
            }
            return s
        }
        set { _rawState = newValue }
    }

    /// Typed child store accessors, built from the internal cache.
    /// Returns the `ChildStores` struct generated by the `@Reducer` macro,
    /// which has typed properties like `children.detail: Store<DetailReducer>?`.
    public var children: R.ChildStores {
        R._makeChildStores(from: _childCache)
    }

    public var _scopeImpl: Store<R> { self }

    // MARK: - Initialiser

    public init(initialState: R.State) {
        self._rawState = initialState
    }

    // MARK: - ScopeImplementation

    @_spi(Internal)
    public func update(_ when: R.When) throws {
        var mutableState = state  // uses getter: injects child/super states
        let dependencies = ReducerDependenciesImpl(node: self, parentStore: self)
        try R.update(when, state: &mutableState, effectsState: &effectsState, dependencies: dependencies)
        applyChildSlots(&mutableState, triggerDefaults: true)
    }

    // Applies dirty child-slot transitions: creates/destroys child stores, resets dirty
    // flags, writes _rawState, then fires defaultTrigger on each new child.
    // _rawState is committed before defaultTrigger so that any @SuperState read inside
    // the child's first update already sees the updated parent state.
    //
    // Reassigning an already-non-nil @SubState is treated exactly like creating a brand-new
    // one: the previous child Store (and everything nested under it) is discarded outright —
    // no grandchild migration, no "carry the old live subtree over" special case. A recreated
    // child gets a fresh Store, its own @SubState descendants are recursively initialized from
    // whatever the newly-assigned State specifies, and triggerDefault fires on it exactly as it
    // would for a genuinely new child. If a reducer wants to preserve something across being
    // recreated, that's its own responsibility to restore in its own defaultWhen (e.g. re-fetch
    // from a dependency), not something the framework carries over silently on its behalf.
    private func applyChildSlots(_ mutableState: inout R.State, triggerDefaults: Bool) {
        var newChildren: [(AnyObject, AnyChildSlot<R.State>)] = []
        for slot in R._childSlots {
            guard slot.isDirty(mutableState) else { continue }
            if slot.isPresent(mutableState) {
                let child = slot.create(mutableState)
                if let childNode = child as? any InjectionTreeNode {
                    childNode._parentNode = self
                }
                // Wire any @SuperState(observed: true) relays now that the child's parent
                // link is established — exactly once, at child-creation time.
                (child as? any _SuperSlotWireable)?._wireSuperSlots()
                // Recursively initialize any @SubState descendants already present in the
                // initial state (dirty flags are read here, before the state getter would
                // reset them via injectIntoParent), then schedule triggerDefault.
                (child as? any _ChildCacheable)?._applyChildSlotsRecursively(
                    state: slot.extractChildState(mutableState),
                    triggerDefaults: false
                )
                newChildren.append((child, slot))
                _childCache[slot.key] = child
            } else {
                _childCache.removeValue(forKey: slot.key)
            }
            slot.resetDirty(&mutableState)
        }
        _rawState = mutableState
        if triggerDefaults {
            for (child, slot) in newChildren {
                slot.triggerDefault(child)
            }
        }
    }

    // MARK: - CustomDebugStringConvertible

    public var debugDescription: String {
        "\(type(of: self)): \(String(describing: _rawState))"
    }
}

// MARK: - _ChildCacheable (fileprivate — recursive descendant initialization support)

fileprivate protocol _ChildCacheable: AnyObject {
    func _applyChildSlotsRecursively(state: Any, triggerDefaults: Bool)
}

extension Store: _ChildCacheable {}

// MARK: - _SuperSlotWireable (fileprivate — @SuperState(observed: true) relay support)

fileprivate protocol _SuperSlotWireable: AnyObject {
    func _wireSuperSlots()
}

extension Store: _SuperSlotWireable {
    /// Subscribes to each `@SuperState(observed: true)` slot's ancestor exactly once, so this
    /// store's `objectWillChange` fires whenever the referenced ancestor's state changes —
    /// even though nothing about this store's own `_rawState` changed. Slots without
    /// `observed: true` have `subscribe == nil` and are skipped.
    fileprivate func _wireSuperSlots() {
        for slot in R._superSlots {
            guard let subscribe = slot.subscribe, let cancellable = subscribe(self) else { continue }
            _superObservers.append(cancellable)
        }
    }
}

// MARK: - Injectable (when State: Injectable)

extension Store: Injectable where R.State: Injectable {
    public static var defaultValue: Store<R> {
        Store<R>(initialState: R.State.defaultValue)
    }
}

// MARK: - ReducerDispatchable

extension Store: ReducerDispatchable {
    public func _callUpdateSubstate<Parent: MiddlewareReducer>(
        _ parentType: Parent.Type,
        when: Any,
        parentState: Parent.State,
        dependencies: ReducerDependencies
    ) throws -> Parent.When? {
        guard let typedWhen = when as? R.When else { return nil }
        return try Parent.updateSubstate(
            R.self,
            childState: state,
            childWhen: typedWhen,
            parentState: parentState,
            dependencies: dependencies
        )
    }
}

// MARK: - ReducerStoreProtocol

extension Store: ReducerStoreProtocol {
    public func _dispatch(_ when: R.When) {
        send(when)
    }
}

// MARK: - HierarchialScopeMiddleWare (MiddlewareReducer only)

extension Store: HierarchialScopeMiddleWare where R: MiddlewareReducer {
    public func updateSubscope<Child: ScopeImplementation>(
        _ event: SubscopeEvent<Child>
    ) throws {
        // Forward first: the child's own update() always runs before any ancestor reacts, so a
        // reaction that goes on to destroy or replace this child subtree can never race with a
        // stale event still being delivered into it — that race is why this order was chosen.
        try event.forward()

        guard let dispatchable = event.child as? any ReducerDispatchable,
              ObjectIdentifier(dispatchable as AnyObject) != ObjectIdentifier(self) else {
            return
        }

        // updateSubstate is read-only over parentState: it only decides, it never mutates.
        // childState here (read inside _callUpdateSubstate) is already the child's post-update
        // state, since event.forward() above already ran. Any reaction routes through
        // send(delegateWhen) below, which applies it via update() like any other event.
        if let delegateWhen = try dispatchable._callUpdateSubstate(
            R.self,
            when: event.when,
            parentState: state,
            dependencies: ReducerDependenciesImpl(node: self, parentStore: self)
        ) {
            send(delegateWhen)
        }
    }
}
