//
//  Store.swift
//  Statoscope
//

import Foundation
import Combine

/// Generic store for any `Reducer` type.
///
/// `Store<R>` replaces the per-reducer `Store` classes previously generated by the `@Reducer`
/// macro. It is fully generic: child store lifecycle, parent state injection, and effect
/// management are driven by the `_childSlots` and `_superSlots` arrays that the `@Reducer`
/// macro generates on the `Reducer` type.
///
/// ## Usage
/// ```swift
/// @Reducer
/// struct CounterReducer {
///     struct State { var count: Int = 0 }
///     enum When { case increment }
///     static func update(_ when: When, state: inout State, ...) throws {
///         state.count += 1
///     }
/// }
///
/// // The macro generates: public typealias Store = Statoscope.Store<CounterReducer>
/// let store = CounterReducer.Store(initialState: .init())
/// store.send(.increment)
/// print(store.state.count) // 1
/// ```
public final class Store<R: Reducer>: Statostore, ObservableObject {

    public typealias When = R.When
    public typealias ScopeImpl = Store<R>

    // MARK: - State storage

    /// Raw state storage. @Published triggers SwiftUI objectWillChange.
    /// Public so macro-generated `injectIntoParent` closures can access `childStore._rawState`
    /// without requiring @_spi imports in user code.
    @Published public var _rawState: R.State

    /// Child store cache — keyed by `AnyChildSlot.key`. Managed during `update()`.
    var _childCache: [AnyHashable: AnyObject] = [:]

    // Used by applyChildSlots to migrate grandchildren when a child store is replaced.
    fileprivate func migrateGrandchildren(from oldStore: any _ChildCacheable) {
        _childCache = oldStore._childCache
        for grandchild in _childCache.values {
            (grandchild as? any InjectionTreeNode)?._parentNode = self
        }
    }

    // Recursively applies child slots using `initialState` (passed by the caller) rather
    // than reading _rawState, so the caller controls which state drives the recursion.
    // Critical: must run before the `state` computed getter resets dirty flags via injectIntoParent.
    fileprivate func _applyChildSlotsRecursively(state initialState: Any, triggerDefaults: Bool) {
        guard var typedState = initialState as? R.State else { return }
        applyChildSlots(&typedState, triggerDefaults: triggerDefaults)
    }

    // MARK: - Public API

    /// Computed state: injects live child states and parent state snapshots before returning.
    ///
    /// Reads `_rawState`, then applies each `_childSlots` `injectIntoParent` closure
    /// (so `state.child` always reflects the current child store's data) and each
    /// `_superSlots` `inject` closure (so `state.parent` always reflects the current
    /// parent store's data). The raw storage is unmodified.
    public var state: R.State {
        get {
            let childSlots = R._childSlots
            let superSlots = R._superSlots
            guard !childSlots.isEmpty || !superSlots.isEmpty else { return _rawState }
            var s = _rawState
            for slot in childSlots {
                slot.injectIntoParent(_childCache[slot.key], &s)
            }
            for slot in superSlots {
                slot.inject(self, &s)
            }
            return s
        }
        set { _rawState = newValue }
    }

    /// Typed child store accessors, built from the internal cache.
    /// Returns the `ChildStores` struct generated by the `@Reducer` macro,
    /// which has typed properties like `children.detail: Store<DetailReducer>?`.
    public var children: R.ChildStores {
        R._makeChildStores(from: _childCache)
    }

    public var _scopeImpl: Store<R> { self }

    // MARK: - Initialiser

    public init(initialState: R.State) {
        self._rawState = initialState
    }

    // MARK: - ScopeImplementation

    @_spi(Internal)
    public func update(_ when: R.When) throws {
        var mutableState = state  // uses getter: injects child/super states
        let dependencies = ReducerDependenciesImpl(node: self, parentStore: self)
        try R.update(when, state: &mutableState, effectsState: &effectsState, dependencies: dependencies)
        applyChildSlots(&mutableState, triggerDefaults: true)
    }

    // Applies dirty child-slot transitions: creates/destroys child stores, resets dirty
    // flags, writes _rawState, then fires defaultTrigger on each new child.
    // _rawState is committed before defaultTrigger so that any @SuperState read inside
    // the child's first update already sees the updated parent state.
    //
    // Pattern 3 — reassign (dirty, old child exists): replace with fresh store and migrate
    //   grandchildren so they survive. triggerDefault is NOT fired (child was already live).
    // Pattern 1/4 — new child (dirty, no old child): create store, recursively initialize
    //   any @SubState descendants already in the initial state (dirty flags are read here,
    //   before the state getter would reset them via injectIntoParent), then fire triggerDefault.
    private func applyChildSlots(_ mutableState: inout R.State, triggerDefaults: Bool) {
        var newChildren: [(AnyObject, AnyChildSlot<R.State>)] = []
        for slot in R._childSlots {
            guard slot.isDirty(mutableState) else { continue }
            if slot.isPresent(mutableState) {
                let oldChild = _childCache[slot.key]
                let child = slot.create(mutableState)
                if let childNode = child as? any InjectionTreeNode {
                    childNode._parentNode = self
                }
                if let oldCacheable = oldChild as? any _ChildCacheable,
                   let newStore = child as? any _ChildCacheable {
                    // Pattern 3: replacing existing child — migrate grandchildren.
                    newStore.migrateGrandchildren(from: oldCacheable)
                } else {
                    // Pattern 1/4: brand-new child — recursively initialize descendants from
                    // the initial state while dirty flags are still set, then schedule triggerDefault.
                    (child as? any _ChildCacheable)?._applyChildSlotsRecursively(
                        state: slot.extractChildState(mutableState),
                        triggerDefaults: false
                    )
                    newChildren.append((child, slot))
                }
                _childCache[slot.key] = child
            } else {
                _childCache.removeValue(forKey: slot.key)
            }
            slot.resetDirty(&mutableState)
        }
        _rawState = mutableState
        if triggerDefaults {
            for (child, slot) in newChildren {
                slot.triggerDefault(child)
            }
        }
    }

    // MARK: - CustomDebugStringConvertible

    public var debugDescription: String {
        "\(type(of: self)): \(String(describing: _rawState))"
    }
}

// MARK: - _ChildCacheable (fileprivate — grandchild migration support)

fileprivate protocol _ChildCacheable: AnyObject {
    var _childCache: [AnyHashable: AnyObject] { get }
    func migrateGrandchildren(from oldStore: any _ChildCacheable)
    func _applyChildSlotsRecursively(state: Any, triggerDefaults: Bool)
}

extension Store: _ChildCacheable {}

// MARK: - Injectable (when State: Injectable)

extension Store: Injectable where R.State: Injectable {
    public static var defaultValue: Store<R> {
        Store<R>(initialState: R.State.defaultValue)
    }
}

// MARK: - ReducerDispatchable

extension Store: ReducerDispatchable {
    public func _callUpdateSubstate<Parent: MiddlewareReducer>(
        _ parentType: Parent.Type,
        when: Any,
        parentState: Parent.State,
        dependencies: ReducerDependencies
    ) throws -> SubstateOutcome<Parent.When> {
        guard let typedWhen = when as? R.When else { return .pass }
        return try Parent.updateSubstate(
            R.self,
            childState: state,
            childWhen: typedWhen,
            parentState: parentState,
            dependencies: dependencies
        )
    }
}

// MARK: - ReducerStoreProtocol

extension Store: ReducerStoreProtocol {
    public func _dispatch(_ when: R.When) {
        send(when)
    }
}

// MARK: - HierarchialScopeMiddleWare (MiddlewareReducer only)

extension Store: HierarchialScopeMiddleWare where R: MiddlewareReducer {
    public func updateSubscope<Child: ScopeImplementation>(
        _ event: SubscopeEvent<Child>
    ) throws {
        var outcome: SubstateOutcome<R.When> = .pass

        if let dispatchable = event.child as? any ReducerDispatchable,
           ObjectIdentifier(dispatchable as AnyObject) != ObjectIdentifier(self) {
            // updateSubstate is read-only over parentState: it only decides, it never mutates.
            // Any reaction comes back through the returned SubstateOutcome and is applied by
            // `send(delegateWhen)` below, which routes through update() like any other event.
            outcome = try dispatchable._callUpdateSubstate(
                R.self,
                when: event.when,
                parentState: state,
                dependencies: ReducerDependenciesImpl(node: self, parentStore: self)
            )
        }

        switch outcome {
        case .pass:
            try event.forward()
        case .react(let delegateWhen):
            // Reaction doesn't invalidate the child — send it, then still forward.
            send(delegateWhen)
            try event.forward()
        case .intercept(let delegateWhen):
            // Reaction may have invalidated the child's subtree — consume the event,
            // do NOT forward it. Forwarding here would deliver `event.when` into state
            // that updateSubstate itself may have just torn down or replaced.
            if let delegateWhen {
                send(delegateWhen)
            }
        }
    }
}
