# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build documentation
      run: >
        rm -rf docs;
        mkdir docs;
        TAG=`git describe --tags --abbrev=0`;
        swift package \
          --allow-writing-to-directory docs/"$TAG" \
          generate-documentation \
          --target Statoscope \
          --output-path docs/"$TAG" \
          --transform-for-static-hosting \
          --hosting-base-path /statoscope/"$TAG";
        sudo chown -R $USER docs;

    - name: Deploy documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        publish_branch: gh-pages
        keep_files: true
